### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by katebogolepova** [Artem-Yakovlev/Family-Circle#1]
1. Старайся как можно реже использовать оператор !!, если у тебя переменная может быть null, это лучше обработать.
2. Здорово, что ты постарался использовать интерфейсы для каждой функциональности в своей программе, но над архитектурой нужно еще поработать, на мой взгляд сейчас она немного перегружена.
3. Когда записываешь что-то в Bundle, создавай константы для ключей, так ты избежишь ошибок, когда будешь доставать значение. Например вот тут вместо "personFullPhoneNumber" лучше использовать константу:
bundle.putString("personFullPhoneNumber", familyInteractor.getActualFamily()
                .getFamilyMembers().get(position).getFullPhoneNumber());
4. По структуре проекта можешь посмотреть хороший пример вот тут https://github.com/matzuk/TestableCodeMobius. Не очень поняла, почему у тебя некоторые вью и презентеры пустые.
5. Если ты наследуешься от фрагмента или активити, то нужно добавлять это слово в конце названия класса, например MainLivePage extends Fragment должен называться MainLivePageFragment

**Comment by Artem-Yakovlev** [comment]
@katebogolepova  Хорошо, обязательно исправлюсь эти моменты
